[tool.pytest.ini_options]
filterwarnings = [
    # Escalate warnings to errors.
    "error",

    # The ply package doesn't close its debug log file. Ignore this warning.
    "ignore::ResourceWarning",
]

[tool.mypy]
warn_return_any = true
warn_unused_configs = true
mypy_path = "$MYPY_CONFIG_FILE_DIR/stubs"

# [[tool.mypy.overrides]]
# module = [
#     "ply",
#     "ply.lex",
#     "ply.yacc",
# ]
# ignore_missing_imports = true
